### ISSUE TITLE
训练参数

### ISSUE THREAD

**Issue by 9Cirno9** [HuiqianLi/ASPS#1]
请问能提供运行train.py时所需的参数吗，谢谢！

**Comment by HuiqianLi** [comment]
你好！配置文件见 [option.py](https://github.com/HuiqianLi/ASPS/blob/master/option.py)
训练所需的 iterations 大约 40 * 400，即约 40 epochs，这里你需要计算自己的数据每个epoch所需iteration；
我使用一张 3090 设置batchsize大小为  4；
输入CNN的图像大小我设置为 320，可以设置更大的，只不过会耗显存；
其他参数都和 option.py 一样~感谢关注:)
