### ISSUE TITLE
您好 想问一下模型输出的内容

### ISSUE THREAD

**Issue by silverdew-wky** [HuiqianLi/ASPS#2]
![image](https://github.com/user-attachments/assets/f22bcf10-3923-434d-9372-34b48bb9102b)
想问一下，模型输出的这三个数值，分别是什么类型的，shape是什么

**Comment by HuiqianLi** [comment]
torch.Size([B, 1, 256, 256]) torch.Size([B, 1]) torch.Size([B, 1, 256, 256])
分别表示 预测的mask，iou分数（1-图像级不确定性），像素级不确定性

**Comment by silverdew-wky** [comment]
![image](https://github.com/user-attachments/assets/c72c759c-caeb-42b0-87f5-3a518a4c2a1b)
model跳转到EfficientSam类后，输出的不是这两个吗，想知道iou分数和像素不确定性的代码在哪里

**Comment by HuiqianLi** [comment]
1. 这个是mask decoder的输出，整个网络的输出在 [return torch.sigmoid(masks), torch.sigmoid(iou_pred), uncertainty_p](
https://github.com/HuiqianLi/ASPS/blob/34e50e8f5b6edfbc797d9782b481d9490064458c/model/Network.py#L40)  

2. iou分数是直接使用了SAM的mask decoder的 iou_predictions输出，就是你上面这个截图里的第二项，它是经过一层MLP的输出，相当于预测一个置信度
3. 像素不确定性也在 Network 文件         [uncertainty_p = 1 - torch.sigmoid(torch.abs(masks))](https://github.com/HuiqianLi/ASPS/blob/34e50e8f5b6edfbc797d9782b481d9490064458c/model/Network.py#L39)
具体解释的话：经过 sigmoid(P) 之后，概率在0.5左右的像素是不确定的，这些值在sigmoid之前在 0 附近。 联想sigmoid(|x|)的图像（下图），sigmoid(|P|) 可以作为置信度，值越大越确定，故用 1-sigmoid(|P|) 作为像素不确定性
![output](https://github.com/user-attachments/assets/6d3df7ec-c275-46ee-8fde-b37620b377d2)

**Comment by silverdew-wky** [comment]
谢谢  讲的真的很详细

**Comment by HuiqianLi** [comment]
不客气，感谢对这篇工作的关注 :)

**Comment by 9Cirno9** [comment]
前辈您好，请问测试中的评估函数里面
polyp_pred = polyp_pred >= 0.5
起到什么作用

**Comment by HuiqianLi** [comment]
> 前辈您好，请问测试中的评估函数里面 polyp_pred = polyp_pred >= 0.5 起到什么作用

把预测图过一个阈值（0.5），这样就得到一个二值图，像素值非0即1

**Comment by 9Cirno9** [comment]
> > 前辈您好，请问测试中的评估函数里面 polyp_pred = polyp_pred >= 0.5 起到什么作用
> 
> 把预测图过一个阈值（0.5），这样就得到一个二值图，像素值非0即1

谢谢！有的代码里是生成0到1的一系列阈值，然后根据阈值对模型的预测掩码做一个二值化处理，然后在每个阈值下做计算，直接取阈值为0.5和它会有较大差异吗，哪个好些呢

**Comment by HuiqianLi** [comment]
> > > 前辈您好，请问测试中的评估函数里面 polyp_pred = polyp_pred >= 0.5 起到什么作用
> > 
> > 
> > 把预测图过一个阈值（0.5），这样就得到一个二值图，像素值非0即1
> 
> 谢谢！有的代码里是生成0到1的一系列阈值，然后根据阈值对模型的预测掩码做一个二值化处理，然后在每个阈值下做计算，直接取阈值为0.5和它会有较大差异吗，哪个好些呢

会有差异，应该每个阈值计算更准确一些吧，但是相对计算也慢，我这边方便计算就直接按0.5了，同样我自己跑的对比方法也是这样算的
