### ISSUE TITLE
CNN的模型是MSCAN-L，那sam-path-b的模型是B-L-0015200.pth，sam-path-h的模型是H-L-0016400.pth吗？

### ISSUE THREAD

**Issue by 253458lgc** [HuiqianLi/ASPS#4]
如果是的，efficient_sam_vitt.pt与efficient_sam_vits.pt的作用又是什么呢？
以及mscan_t.pth有用途吗？

**Comment by HuiqianLi** [comment]
efficient_sam_vitt.pt与efficient_sam_vits.pt 可以用来替换SAM，需要把args.sam设置成efficient_sam_vitt，[这里](https://github.com/HuiqianLi/ASPS/blob/5827d67cb11ffc4bee946adad382f97900ed768e/efficient_sam/build_efficient_sam.py#L13)的路径修改成efficient_sam_vitt.pt的路径；
mscan_t.pth可以用来替换MSCAN-L，args.mscan参数改成tiny。
这几个模型参数比较小，做对比实验的时候用了一下，如果没有需要可以不用管它。
