### ISSUE TITLE
重新训练并验证的效果与论文相差较大

### ISSUE THREAD

**Issue by rhyhck** [HuiqianLi/ASPS#5]
作者您好，我根据readme的提示训练并测试了模型，由于显存有限，我把bach_size调到了1，其他条件都保持不变的情况下，我用vit_b，模型，在CVC-ClinicDB数据集上测试的准确率如下，与论文给的数据相差较大，想请教您我是否遗漏了什么呢？期待您的回复~
![test](https://github.com/user-attachments/assets/ff2cb0ce-02d5-4b01-a3b4-183b6bcd1eb7)

**Comment by HuiqianLi** [comment]
bach_size在训练时的影响确实是存在的。bach_size调到了1的话，对应的'--save_iter'保存轮次和'--iterations'训练轮次也得进行修改，我这里设置的 400\*40 是 (1450/4)*40，数据集1450张batchsize为4训练40epochs，可能得修改成1450\*40。其次的话显存不够还可以修改cnn网络 mscan 的尺寸，使用tiny模型，但是效果应该也会差一些。

这行也得改改，这行需要选择对应的SAM模型，[parser.add_argument('--sam', type=str, default='efficient_sam_vitt', help='vit_b or vit_h or efficien](https://github.com/HuiqianLi/ASPS/blob/5827d67cb11ffc4bee946adad382f97900ed768e/option.py#L20)

我这里有记录之前做过换模型的实验，效果与论文差的不大。
![Snipaste_2024-12-05_16-57-07](https://github.com/user-attachments/assets/59b932bb-f6e2-4ab4-8fcd-34803a9e9d93)

此外，如果您有这方面研究兴趣的话，最近有看到[在内窥镜数据上预训练的backbone](https://huggingface.co/tgwboers/GastroNet-5M_Pretrained_Weights)，或许把CNN网络替换成这个已经预训练过的ResNet50效果会好？

**Comment by rhyhck** [comment]
> bach_size在训练时的影响确实是存在的。bach_size调到了1的话，对应的'--save_iter'保存轮次和'--iterations'训练轮次也得进行修改，我这里设置的 400*40 是 (1450/4)*40，数据集1450张batchsize为4训练40epochs，可能得修改成1450*40。其次的话显存不够还可以修改cnn网络 mscan 的尺寸，使用tiny模型，但是效果应该也会差一些。
> 
> 这行也得改改，这行需要选择对应的SAM模型，[parser.add_argument('--sam', type=str, default='efficient_sam_vitt', help='vit_b or vit_h or efficien](https://github.com/HuiqianLi/ASPS/blob/5827d67cb11ffc4bee946adad382f97900ed768e/option.py#L20)
> 
> 我这里有记录之前做过换模型的实验，效果与论文差的不大。 ![Snipaste_2024-12-05_16-57-07](https://private-user-images.githubusercontent.com/44128124/392733438-59b932bb-f6e2-4ab4-8fcd-34803a9e9d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDAzNjUsIm5iZiI6MTczMzQwMDA2NSwicGF0aCI6Ii80NDEyODEyNC8zOTI3MzM0MzgtNTliOTMyYmItZjZlMi00YWI0LThmY2QtMzQ4MDNhOWU5ZDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyMDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2M0YjhmNzIxYzk2N2JmOGRiMmIwMDJlMTdmOTI2ZDcyMzg1MzJhMGVhYWViYTVjNWY3OTdjNDc4YjdiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k-dd5H5zHA99oBUjyRJj6f6Djf_H18WMC_OtrbrbKJM)
> 
> 此外，如果您有这方面研究兴趣的话，最近有看到[在内窥镜数据上预训练的backbone](https://huggingface.co/tgwboers/GastroNet-5M_Pretrained_Weights)，或许把CNN网络替换成这个已经预训练过的ResNet50效果会好？
非常感谢您的回复，我再去试试修改iterations，请问对于efficient_sam + mscan-L, 您是用以下图片中的pth训练的吗？
[
![pth截图](https://github.com/user-attachments/assets/b515f10e-d50a-4fa5-ada2-98efc576c435)
](url)

期待您的的回复~

**Comment by HuiqianLi** [comment]
> > bach_size在训练时的影响确实是存在的。bach_size调到了1的话，对应的'--save_iter'保存轮次和'--iterations'训练轮次也得进行修改，我这里设置的 400*40 是 (1450/4)_40，数据集1450张batchsize为4训练40epochs，可能得修改成1450_40。其次的话显存不够还可以修改cnn网络 mscan 的尺寸，使用tiny模型，但是效果应该也会差一些。
> > 这行也得改改，这行需要选择对应的SAM模型，[parser.add_argument('--sam', type=str, default='efficient_sam_vitt', help='vit_b or vit_h or efficien](https://github.com/HuiqianLi/ASPS/blob/5827d67cb11ffc4bee946adad382f97900ed768e/option.py#L20)
> > 我这里有记录之前做过换模型的实验，效果与论文差的不大。 ![Snipaste_2024-12-05_16-57-07](https://private-user-images.githubusercontent.com/44128124/392733438-59b932bb-f6e2-4ab4-8fcd-34803a9e9d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDAzNjUsIm5iZiI6MTczMzQwMDA2NSwicGF0aCI6Ii80NDEyODEyNC8zOTI3MzM0MzgtNTliOTMyYmItZjZlMi00YWI0LThmY2QtMzQ4MDNhOWU5ZDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyMDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2M0YjhmNzIxYzk2N2JmOGRiMmIwMDJlMTdmOTI2ZDcyMzg1MzJhMGVhYWViYTVjNWY3OTdjNDc4YjdiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k-dd5H5zHA99oBUjyRJj6f6Djf_H18WMC_OtrbrbKJM)
> > 此外，如果您有这方面研究兴趣的话，最近有看到[在内窥镜数据上预训练的backbone](https://huggingface.co/tgwboers/GastroNet-5M_Pretrained_Weights)，或许把CNN网络替换成这个已经预训练过的ResNet50效果会好？
> > 非常感谢您的回复，我再去试试修改iterations，请问对于efficient_sam + mscan-L, 您是用以下图片中的pth训练的吗？
> > [
> > ![pth截图](https://private-user-images.githubusercontent.com/118146110/392810238-b515f10e-d50a-4fa5-ada2-98efc576c435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDc1NjgsIm5iZiI6MTczMzQwNzI2OCwicGF0aCI6Ii8xMTgxNDYxMTAvMzkyODEwMjM4LWI1MTVmMTBlLWQ1MGEtNGZhNS1hZGEyLTk4ZWZjNTc2YzQzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQxNDAxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2Q4YjgyMDEyNmM4NDk0MjU0ZmFmZWU1MTZiMmZlOTdkNWQyMTVmMWU4NjRmNDk2MmQ0NGRhNzZiMzA1YmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WtpIKbb8F2jZkSFgre7Kf4k-cJNhSZgJKOU-pOiMrfQ)
> > ](url)
> 
> 期待您的的回复~

是的
